Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2018-10, with the labels that each got.

#259 Added schema compliance tests and applied a few changes
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/MSIDOAuth2Constants.h
  IdentityCore/src/MSIDOAuth2Constants.m
  IdentityCore/src/cache/key/MSIDDefaultCredentialCacheKey.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.h
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
  IdentityCore/src/oauth2/MSIDOauth2Factory.m
  IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m
  IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
  IdentityCore/src/oauth2/account/MSIDAccountType.m
  IdentityCore/src/oauth2/token/MSIDBaseToken.h
  IdentityCore/src/oauth2/token/MSIDBaseToken.m
  IdentityCore/src/oauth2/token/MSIDCredentialType.m
  IdentityCore/src/oauth2/token/MSIDLegacyAccessToken.m
  IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
  IdentityCore/src/util/NSOrderedSet+MSIDExtensions.h
  IdentityCore/src/util/NSOrderedSet+MSIDExtensions.m
  IdentityCore/src/validation/MSIDAuthorityFactory.m
  IdentityCore/src/validation/MSIDB2CAuthority.h
  IdentityCore/src/validation/MSIDB2CAuthority.m
  IdentityCore/src/webview/systemWebview/ios/MSIDAuthenticationSession.m
  IdentityCore/tests/MSIDAADAuthorityTests.m
  IdentityCore/tests/MSIDAADOauth2FactoryTests.m
  IdentityCore/tests/MSIDAADTokenResponseTests.m
  IdentityCore/tests/MSIDAADV1Oauth2FactoryTests.m
  IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m
  IdentityCore/tests/MSIDAccessTokenTests.m
  IdentityCore/tests/MSIDB2CAuthorityTests.m
  IdentityCore/tests/MSIDBaseTokenTests.m
  IdentityCore/tests/MSIDCredentialCacheItemTests.m
  IdentityCore/tests/MSIDCredentialTypeTests.m
  IdentityCore/tests/MSIDIdTokenTests.m
  IdentityCore/tests/MSIDJsonSerializerTests.m
  IdentityCore/tests/MSIDKeyedArchiverSerializerTests.m
  IdentityCore/tests/MSIDLegacyAccessTokenTests.m
  IdentityCore/tests/MSIDLegacyRefreshTokenTests.m
  IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m
  IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m
  IdentityCore/tests/MSIDOauth2FactoryTests.m
  IdentityCore/tests/MSIDOrderedSetExtensionsTests.m
  IdentityCore/tests/MSIDRefreshTokenTests.m
  IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m
Labels: msal_0.2.1

#265 Patch TeamID when receiving errSecInteractionNotAllowed
  IdentityCore/src/util/MSIDKeychainUtil.m
Labels: 2.7.4

#264 Fixed extended expires on key to be compliant with cache schema
  IdentityCore/src/MSIDOAuth2Constants.m
  IdentityCore/tests/MSIDAccessTokenTests.m
  IdentityCore/tests/MSIDCredentialCacheItemTests.m
  IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m
Labels: 2.7.4

#263 Switched legacy cache fallbacks to rely on accounts instead of ID tokens (cache lookup optimization)
  IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.h
  IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.h
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/oauth2/MSIDIdTokenClaims.h
  IdentityCore/src/oauth2/MSIDIdTokenClaims.m
  IdentityCore/src/oauth2/aad_v1/MSIDAADV1IdTokenClaims.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2IdTokenClaims.m
  IdentityCore/tests/MSIDAccountCredentialsCacheTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyTokenCacheIntegrationTests.m
Labels: 2.7.4

#261 fixed object equality issue
  IdentityCore/src/cache/token/MSIDAccountCacheItem.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
  IdentityCore/tests/MSIDAccountCacheItemTests.m
  IdentityCore/tests/MSIDCredentialCacheItemTests.m
  IdentityCore/tests/MSIDKeyedArchiverSerializerTests.m
  IdentityCore/tests/MSIDLegacyAccessTokenTests.m
  IdentityCore/tests/MSIDLegacyRefreshTokenTests.m
  IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m
  IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
Labels: msal_0.3.0
