Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2018-08, with the labels that each got.

#184 Merge changes in release/1.0.0 to dev
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/IdentityCore.pch
  IdentityCore/src/IdentityCore_Internal.h
  IdentityCore/src/cache/MSIDMacTokenCache.h
  IdentityCore/src/cache/MSIDMacTokenCache.m
  IdentityCore/src/oauth2/MSIDOauth2Factory.m
  IdentityCore/src/oauth2/MSIDWebviewFactory.m
  IdentityCore/src/webview/MSIDWebviewAuthorization.m
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDClientTLSHandler.m
  IdentityCore/src/webview/systemWebview/ios/MSIDSFAuthenticationSession.h
  IdentityCore/src/webview/systemWebview/ios/MSIDSFAuthenticationSession.m
  IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.h
  IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m
  IdentityCore/src/webview/systemWebview/ios/MSIDSystemWebviewController.h
  IdentityCore/src/webview/systemWebview/ios/MSIDSystemWebviewController.m
  IdentityCore/tests/util/MSIDTestIdTokenUtil.h
  IdentityCore/tests/util/MSIDTestIdTokenUtil.m
Labels: msal_0.1.4

#186 Skip tombstones in mac token cache
  IdentityCore/src/cache/MSIDMacTokenCache.m
  IdentityCore/src/cache/ios/MSIDKeychainTokenCache.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.h
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
  IdentityCore/tests/integration/mac/MSIDMacTokenCacheIntegrationTests.m
Labels: 2.7.0 release

#189 State verification only to be done on redirect uri
  IdentityCore/src/oauth2/MSIDWebviewFactory.h
  IdentityCore/src/oauth2/MSIDWebviewFactory.m
  IdentityCore/src/webview/MSIDWebviewAuthorization.m
  IdentityCore/tests/MSIDAADWebviewFactoryTests.m
  IdentityCore/tests/MSIDWebviewFactoryTests.m
Labels: msal_0.1.4

#192 Move state verification logic to OAuthResponse
  IdentityCore/src/oauth2/MSIDWebviewFactory.h
  IdentityCore/src/oauth2/MSIDWebviewFactory.m
  IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
  IdentityCore/src/webview/MSIDWebviewAuthorization.m
  IdentityCore/src/webview/MSIDWebviewSession.h
  IdentityCore/src/webview/MSIDWebviewSession.m
  IdentityCore/src/webview/response/MSIDWebOAuth2Response.h
  IdentityCore/src/webview/response/MSIDWebOAuth2Response.m
  IdentityCore/tests/MSIDAADWebviewFactoryTests.m
  IdentityCore/tests/MSIDWebAADAuthResponseTests.m
  IdentityCore/tests/MSIDWebOAuth2ResponseTests.m
  IdentityCore/tests/MSIDWebviewAuthorizationTests.m
  IdentityCore/tests/MSIDWebviewFactoryTests.m
Labels: msal_0.1.4

#193 Add conditionals to tests
  IdentityCore/tests/MSIDSystemWebviewControllerTests.m
Labels: msal_0.1.4

#200 Moved consumers authority check to base AAD Oauth2 Factory and renamed aliases methods
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
  IdentityCore/src/oauth2/MSIDOauth2Factory.h
  IdentityCore/src/oauth2/MSIDOauth2Factory.m
  IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m
  IdentityCore/src/oauth2/aad_v1/MSIDAADV1Oauth2Factory.m
  IdentityCore/tests/MSIDAADOauth2FactoryTests.m
  IdentityCore/tests/MSIDAADV1Oauth2FactoryTests.m
  IdentityCore/tests/MSIDOauth2FactoryTests.m
Labels: msal_0.1.4

#199 Added unmapped error to MSID error mapping
  IdentityCore/src/MSIDError.m
Labels: msal_0.1.4

#187 Added additional automation lab properties
  IdentityCore/tests/automation/MSIDTestAutomationConfiguration.h
  IdentityCore/tests/automation/MSIDTestAutomationConfiguration.m
  IdentityCore/tests/automation/MSIDTestAutomationConfigurationRequest.h
  IdentityCore/tests/automation/MSIDTestAutomationConfigurationRequest.m
Labels: msal_0.1.4

#201 Clear cache for account in other accessors from default accessor
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
Labels: msal_0.1.4

#202 Added token cache optimizations
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/oauth2/MSIDWebviewFactory.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2IdTokenClaims.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
Labels: msal_0.1.4

#204 Merge release 1.0.0 back to dev (cache optimizations and tombstone changes)
  IdentityCore/src/cache/MSIDMacTokenCache.m
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/ios/MSIDKeychainTokenCache.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.h
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
  IdentityCore/src/oauth2/MSIDWebviewFactory.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2IdTokenClaims.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDDefaultTokenCacheIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/mac/MSIDMacTokenCacheIntegrationTests.m
Labels: msal_0.1.4

#206 PKeyAuth handling and scopes handling fix
  IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2WebviewFactory.m
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDPKeyAuthHandler.m
  IdentityCore/tests/MSIDAADV1WebviewFactoryTests.m
  IdentityCore/tests/MSIDAADWebviewFactoryTests.m
Labels: msal_0.1.4

#188 Fix http request error handling
  IdentityCore/src/MSIDError.h
  IdentityCore/src/MSIDError.m
  IdentityCore/src/MSIDOAuth2Constants.h
  IdentityCore/src/MSIDOAuth2Constants.m
  IdentityCore/src/network/MSIDHttpRequest.h
  IdentityCore/src/network/MSIDHttpRequest.m
  IdentityCore/src/network/MSIDHttpRequestProtocol.h
  IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.h
  IdentityCore/src/network/error_handler/MSIDAADRequestErrorHandler.m
  IdentityCore/src/oauth2/aad_base/MSIDAADOauth2Factory.m
  IdentityCore/src/oauth2/token/MSIDAccessToken.m
  IdentityCore/src/util/NSURL+MSIDExtensions.m
  IdentityCore/tests/MSIDAADRequestErrorHandlerTests.m
  IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m
  IdentityCore/tests/MSIDCredentialCacheItemTests.m
  IdentityCore/tests/MSIDURLExtensionsTests.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDHttpRequestIntegrationTests.m
  IdentityCore/tests/util/cache/MSIDTestTokenResponse.m
Labels: msal_0.1.5

#207 Fix MSIDWebAADAuthResponse to extract cloud instance host
  IdentityCore/src/util/NSURL+MSIDExtensions.h
  IdentityCore/src/util/NSURL+MSIDExtensions.m
  IdentityCore/src/webview/response/MSIDWebAADAuthResponse.m
  IdentityCore/tests/MSIDURLExtensionsTests.m
Labels: msal_0.1.5

#214 Revise utility - NSDictionary extension
  IdentityCore/src/util/NSDictionary+MSIDExtensions.h
  IdentityCore/src/util/NSDictionary+MSIDExtensions.m
  IdentityCore/tests/MSIDDictionaryExtensionsTests.m
  IdentityCore/tests/MSIDURLExtensionsTests.m
  IdentityCore/tests/MSIDWebviewFactoryTests.m
Labels: msal_0.1.5
