Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2019-04, with the labels that each got.

#410 Fixed analyser warnings
  IdentityCore/src/cache/ios/MSIDKeychainTokenCache.m
  IdentityCore/src/cache/key/MSIDCacheKey.h
Labels: broker

#415 Added NSDictionary helper method
  IdentityCore/src/util/NSDictionary+MSIDExtensions.h
  IdentityCore/src/util/NSDictionary+MSIDExtensions.m
  IdentityCore/tests/MSIDDictionaryExtensionsTests.m
Labels: adal_2.7.10

#411 Claims request
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/MSIDJsonSerializer.m
  IdentityCore/src/claims/MSIDClaimsRequest+ClientCapabilities.h
  IdentityCore/src/claims/MSIDClaimsRequest+ClientCapabilities.m
  IdentityCore/src/claims/MSIDClaimsRequest.h
  IdentityCore/src/claims/MSIDClaimsRequest.m
  IdentityCore/src/claims/MSIDIndividualClaimRequest.h
  IdentityCore/src/claims/MSIDIndividualClaimRequest.m
  IdentityCore/src/claims/MSIDIndividualClaimRequestAdditionalInfo.h
  IdentityCore/src/claims/MSIDIndividualClaimRequestAdditionalInfo.m
  IdentityCore/src/oauth2/MSIDOauth2Factory.m
  IdentityCore/src/oauth2/MSIDWebviewFactory.m
  IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2WebviewFactory.m
  IdentityCore/src/parameters/MSIDInteractiveRequestParameters.m
  IdentityCore/src/parameters/MSIDRequestParameters.h
  IdentityCore/src/parameters/MSIDRequestParameters.m
  IdentityCore/src/requests/MSIDBrokerTokenRequest.m
  IdentityCore/src/requests/MSIDSilentTokenRequest.m
  IdentityCore/src/requests/sdk/adal/MSIDLegacyBrokerTokenRequest.m
  IdentityCore/src/util/MSIDClientCapabilitiesUtil.m
  IdentityCore/tests/MSIDClaimsRequestTests.m
  IdentityCore/tests/MSIDClientCapabilitiesTests.m
  IdentityCore/tests/integration/ios/MSIDBrokerTokenRequestTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m
  IdentityCore/tests/integration/ios/MSIDLegacyBrokerRequestTests.m
  IdentityCore/tests/mocks/MSIDClaimsRequestMock.h
  IdentityCore/tests/mocks/MSIDClaimsRequestMock.m
  IdentityCore/tests/util/network/MSIDTestURLSession.m
Labels: build-2019

#424 Moved macOS keychain file under macOS folder
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.h
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
Labels: build-2019

#419 Network configuration object integration
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/configuration/MSIDConfiguration.h
  IdentityCore/src/configuration/MSIDNetworkConfiguration.h
  IdentityCore/src/configuration/MSIDNetworkConfiguration.m
  IdentityCore/src/network/MSIDHttpRequest.h
  IdentityCore/src/network/MSIDHttpRequest.m
  IdentityCore/src/network/MSIDURLSessionManager.h
  IdentityCore/src/network/MSIDURLSessionManager.m
  IdentityCore/src/parameters/MSIDInteractiveRequestParameters.m
  IdentityCore/src/validation/MSIDAADAuthority.m
  IdentityCore/src/validation/MSIDADFSAuthority.m
  IdentityCore/src/validation/MSIDAuthority+Internal.h
  IdentityCore/src/validation/MSIDAuthority.m
  IdentityCore/src/validation/MSIDB2CAuthority.h
  IdentityCore/src/validation/MSIDB2CAuthority.m
  IdentityCore/src/webview/systemWebview/ios/MSIDSystemWebviewController.m
  IdentityCore/tests/MSIDB2CAuthorityTests.m
  IdentityCore/tests/MSIDInteractiveRequestParametersTests.m
Labels: build-2019

#431 Fix on B2C validation copyWithZone
  IdentityCore/src/validation/MSIDB2CAuthority.m
  IdentityCore/tests/MSIDB2CAuthorityTests.m
Labels: build-2019

#433 Improve B2C non tfp authority handling
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.h
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
  IdentityCore/src/oauth2/b2c/MSIDB2COauth2Factory.m
  IdentityCore/src/validation/MSIDAuthority.m
  IdentityCore/src/validation/MSIDAuthorityFactory.h
  IdentityCore/src/validation/MSIDAuthorityFactory.m
  IdentityCore/src/validation/MSIDB2CAuthority.m
  IdentityCore/tests/MSIDB2COauth2FactoryTests.m
Labels: build-2019

#437 Don't go to broker for consumer authority
  IdentityCore/src/validation/MSIDAADAuthority.m
Labels: build-2019

#439 Merge release 1.2.0 to dev
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.h
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
  IdentityCore/src/oauth2/b2c/MSIDB2COauth2Factory.m
  IdentityCore/src/validation/MSIDAADAuthority.m
  IdentityCore/src/validation/MSIDAuthority.m
  IdentityCore/src/validation/MSIDAuthorityFactory.h
  IdentityCore/src/validation/MSIDAuthorityFactory.m
  IdentityCore/src/validation/MSIDB2CAuthority.m
  IdentityCore/tests/MSIDB2COauth2FactoryTests.m
Labels: build-2019

#416 Add tenant id to MSIDAccount
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
  IdentityCore/src/oauth2/account/MSIDAccount.h
  IdentityCore/src/oauth2/account/MSIDAccount.m
  IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m
  IdentityCore/tests/MSIDAADOauth2FactoryTests.m
  IdentityCore/tests/MSIDAADV1Oauth2FactoryTests.m
  IdentityCore/tests/MSIDAADV2Oauth2FactoryTests.m
  IdentityCore/tests/MSIDAccountCredentialsCacheTests.m
  IdentityCore/tests/MSIDAccountTests.m
  IdentityCore/tests/MSIDLegacyAccessTokenTests.m
  IdentityCore/tests/MSIDLegacyRefreshTokenTests.m
  IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m
  IdentityCore/tests/MSIDTokenResponseTests.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/ios/MSIDLegacyBrokerResponseHandlerTests.m
  IdentityCore/tests/util/MSIDTestIdTokenUtil.h
  IdentityCore/tests/util/MSIDTestIdTokenUtil.m
  IdentityCore/tests/util/cache/MSIDTestCacheUtil.h
  IdentityCore/tests/util/cache/MSIDTestCacheUtil.m
  IdentityCore/tests/util/cache/MSIDTestTokenResponse.m
Labels: msal-0.4.1
