Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2019-05, with the labels that each got.

#447 Better error handling for CBA cancellation
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
Labels: broker

#449 Don't initialize refresh token object without refresh token
  IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
Labels: broker

#451 Merge 1.1.1 hot fix to master
  IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
Labels: broker

#452 Merge 1.1.1 to dev
  IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
Labels: broker

#453 Merge latest hot fix changes into release/1.3.0 branch
  IdentityCore/src/oauth2/token/MSIDLegacyRefreshToken.m
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler+iOS.h
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
Labels: 0.5.0

#423 Send raw client telemetry to observer
  IdentityCore/src/telemetry/MSIDTelemetryEventStrings.h
  IdentityCore/src/telemetry/MSIDTelemetryEventStrings.m
  IdentityCore/src/telemetry/MSIDTelemetryHttpEvent.m
  IdentityCore/tests/integration/MSIDTelemetryAggregatedTests.m
  IdentityCore/tests/integration/MSIDTelemetryDefaultTests.m
Labels: msal-0.4.1

#455 Don't log error level logs for non critical errors
  IdentityCore/src/oauth2/MSIDOauth2Factory.m
  IdentityCore/src/oauth2/token/MSIDAccessToken.m
  IdentityCore/src/oauth2/token/MSIDBaseToken.m
  IdentityCore/src/oauth2/token/MSIDIdToken.m
  IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m
  IdentityCore/src/oauth2/token/MSIDRefreshToken.m
  IdentityCore/src/util/NSDictionary+MSIDExtensions.m
Labels: 0.5.0

#465 Merge 1.1.2 hotfix into 1.2.2 hotfix
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2BrokerResponse.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m
Labels: broker

#466 Merge 1.2.2 into master
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2BrokerResponse.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m
Labels: broker

#467 Merge 1.2.2 into dev
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2BrokerResponse.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m
Labels: broker
