Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2019-11, with the labels that each got.

#604 Expose interaction required OAuth error
  IdentityCore/src/MSIDError.m
Labels: SSO-extension

#600 Componentize macOS ACL keychain operations
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.h
  IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.m
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.h
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
  IdentityCore/src/cache/mac/MSIDMacLegacyCachePersistenceHandler.h
  IdentityCore/src/cache/mac/MSIDMacLegacyCachePersistenceHandler.m
  IdentityCore/tests/MSIDMacACLKeychainAccessorTests.m
  IdentityCore/tests/MSIDMacLegacyCachePersistenceHandlerTests.m
Labels: msal-1.0.3

#611 Don't log intune enrollment ID error
  IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m
Labels: msal-1.0.3

#612 Improve error logging when creating claims
  IdentityCore/src/oauth2/aad_v1/MSIDAADV1IdTokenClaims.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2IdTokenClaims.m
  IdentityCore/src/oauth2/b2c/MSIDB2CIdTokenClaims.m
Labels: msal-1.0.3

#615 Fixed warnings in automation
  IdentityCore/src/controllers/broker/MSIDBrokerInteractiveController.m
  IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.m
  IdentityCore/tests/automation/shared/MSIDAutomationTestResult.m
  IdentityCore/tests/automation/shared/MSIDAutomationUserInformation.m
  IdentityCore/tests/automation/ui_app_lib/MSIDClearCookiesTestAction.m
  IdentityCore/tests/automation/ui_app_lib/ios/MSIDClearKeychainTestAction.m
  IdentityCore/tests/automation/ui_app_lib/ios/MSIDOpenURLAction.m
  IdentityCore/tests/automation/ui_app_lib/ui_common/ios/MSIDAutomationPassedInWebViewController.m
  IdentityCore/tests/automation/ui_app_lib/ui_common/ios/MSIDAutomationRequestViewController.m
  IdentityCore/xcconfig/identitycore__tests__ios.xcconfig
  IdentityCore/xcconfig/identitycore__tests__mac.xcconfig
Labels: SSO-extension

#618 Fix broker build (SSO branch)
  IdentityCore/src/controllers/broker/MSIDBrokerInteractiveController.m
Labels: SSO-extension

#622 Merge release 1.3.8 into dev
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.h
  IdentityCore/src/cache/mac/MSIDMacACLKeychainAccessor.m
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.h
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
  IdentityCore/src/cache/mac/MSIDMacLegacyCachePersistenceHandler.h
  IdentityCore/src/cache/mac/MSIDMacLegacyCachePersistenceHandler.m
  IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m
  IdentityCore/src/oauth2/aad_v1/MSIDAADV1IdTokenClaims.m
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2IdTokenClaims.m
  IdentityCore/src/oauth2/b2c/MSIDB2CIdTokenClaims.m
  IdentityCore/tests/MSIDMacACLKeychainAccessorTests.m
  IdentityCore/tests/MSIDMacLegacyCachePersistenceHandlerTests.m
  changelog.txt
Labels: needs-review

#624 SSO extension extra params
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/MSIDBrokerConstants.h
  IdentityCore/src/MSIDBrokerConstants.m
  IdentityCore/src/MSIDConstants.h
  IdentityCore/src/MSIDConstants.m
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.h
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.m
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.h
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.m
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
  IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m
  IdentityCore/src/util/NSDictionary+MSIDExtensions.h
  IdentityCore/src/util/NSDictionary+MSIDExtensions.m
Labels: SSO-extension, needs-review

#628 SSO extension errors
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationResponse.h
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationResponse.m
  IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.h
  IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m
  IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m
  IdentityCore/tests/MSIDAccountTests.m
  IdentityCore/tests/MSIDBrokerOperationAccountResponseTests.m
  IdentityCore/tests/MSIDBrokerOperationRemoveAccountRequestTests.m
Labels: SSO-extension, needs-review

#631 Fixed Identitycore build for macOS
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/IdentityCore.pch
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.h
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.m
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.h
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.m
  IdentityCore/src/controllers/broker/MSIDSSOExtensionInteractiveTokenRequestController.h
  IdentityCore/src/controllers/broker/MSIDSSOExtensionSilentTokenRequestController.h
  IdentityCore/src/controllers/broker/ios/MSIDBrokerInteractiveController.h
  IdentityCore/src/controllers/broker/ios/MSIDBrokerInteractiveController.m
  IdentityCore/src/parameters/MSIDRequestParameters+Broker.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.h
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionRequestDelegate+Internal.h
  IdentityCore/src/requests/broker/MSIDSSOExtensionRequestDelegate.h
  IdentityCore/src/requests/broker/MSIDSSOExtensionRequestDelegate.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.h
  IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionTokenRequestDelegate.h
  IdentityCore/src/util/ASAuthorizationSingleSignOnProvider+MSIDExtensions.h
  IdentityCore/src/util/ASAuthorizationSingleSignOnProvider+MSIDExtensions.m
Labels: needs-review

#634 Fixed functions/methods with no prefix
  IdentityCore/src/MSIDDeviceId.m
  IdentityCore/src/oauth2/MSIDTokenResponse.m
  IdentityCore/src/oauth2/aad_base/MSIDAADTokenResponse.m
  IdentityCore/src/util/MSIDJWTHelper.m
  IdentityCore/src/util/NSData+JWT.h
  IdentityCore/src/util/NSData+JWT.m
  IdentityCore/src/util/NSDictionary+MSIDExtensions.h
  IdentityCore/src/util/NSDictionary+MSIDExtensions.m
  IdentityCore/tests/MSIDDictionaryExtensionsTests.m
Labels: needs-review

#632 Return authority from SSO extension
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationTokenResponse.h
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationTokenResponse.m
  IdentityCore/src/parameters/MSIDRequestParameters.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
Labels: SSO-extension, needs-review
