Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2019-12, with the labels that each got.

#638 SSO Login & Refresh operations tests
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/MSIDJsonSerializableFactory.m
  IdentityCore/src/broker_operation/request/MSIDBrokerOperationRequest.m
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.h
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.m
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.h
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.m
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
  IdentityCore/src/cache/MSIDKeychainTokenCache.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.h
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
  IdentityCore/src/configuration/MSIDConfiguration.m
  IdentityCore/src/oauth2/MSIDOauth2Factory.h
  IdentityCore/src/oauth2/account/MSIDAccount.m
  IdentityCore/src/oauth2/account/MSIDAccountIdentifier.h
  IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m
  IdentityCore/src/oauth2/token/MSIDBaseToken.h
  IdentityCore/src/oauth2/token/MSIDBaseToken.m
  IdentityCore/src/validation/MSIDAuthority.m
  IdentityCore/tests/MSIDAccountTests.m
  IdentityCore/tests/MSIDBaseTokenTests.m
  IdentityCore/tests/MSIDBrokerOperationInteractiveTokenRequestTests.m
  IdentityCore/tests/MSIDBrokerOperationRequestTests.m
  IdentityCore/tests/MSIDBrokerOperationSilentTokenRequestTests.m
  IdentityCore/tests/MSIDBrokerOperationTokenRequestTests.m
  IdentityCore/tests/MSIDCacheItemJsonSerializerTests.m
  IdentityCore/tests/MSIDCredentialCacheItemTests.m
  IdentityCore/tests/MSIDIdTokenTests.m
  IdentityCore/tests/MSIDLegacyAccessTokenTests.m
  IdentityCore/tests/MSIDLegacyRefreshTokenTests.m
  IdentityCore/tests/MSIDLegacySingleResourceTokenTests.m
  IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m
  IdentityCore/tests/MSIDRefreshTokenTests.m
Labels: SSO-extension, needs-review

#642 SSO response tests
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationResponse.m
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationTokenResponse.h
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationTokenResponse.m
  IdentityCore/tests/MSIDBrokerOperationResponseTests.m
  IdentityCore/tests/MSIDBrokerOperationTokenResponseTests.m
Labels: SSO-extension, needs-review

#646 SSO extension bug fixes
  IdentityCore/src/controllers/MSIDLocalInteractiveController.m
  IdentityCore/src/controllers/MSIDSilentController.m
  IdentityCore/src/controllers/broker/MSIDSSOExtensionInteractiveTokenRequestController.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionTokenRequestDelegate.m
Labels: needs-review

#649 Account lookup fix when no refresh tokens present
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/intune/MSIDIntuneMAMResourcesCache.m
  IdentityCore/src/logger/MSIDMaskedUsernameLogParameter.m
  IdentityCore/tests/MSIDMaskedUsernameLogParameterTests.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  changelog.txt
Labels: needs-review

#650 Release 1.3.10
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/intune/MSIDIntuneMAMResourcesCache.m
  IdentityCore/src/logger/MSIDMaskedUsernameLogParameter.m
  IdentityCore/tests/MSIDMaskedUsernameLogParameterTests.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  changelog.txt
Labels: needs-review

#651 Merge release 1.3.10 into dev
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/intune/MSIDIntuneMAMResourcesCache.m
  IdentityCore/src/logger/MSIDMaskedUsernameLogParameter.m
  IdentityCore/tests/MSIDMaskedUsernameLogParameterTests.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  changelog.txt
Labels: needs-review

#653 Allow running SSO extension and legacy broker in hybrid mode
  IdentityCore/src/MSIDBrokerConstants.h
  IdentityCore/src/MSIDBrokerConstants.m
  IdentityCore/src/controllers/MSIDRequestControllerFactory.m
  IdentityCore/src/controllers/broker/ios/MSIDBrokerInteractiveController.h
  IdentityCore/src/controllers/broker/ios/MSIDBrokerInteractiveController.m
  IdentityCore/src/oauth2/MSIDBrokerResponse+Internal.h
  IdentityCore/src/oauth2/MSIDBrokerResponse.h
  IdentityCore/src/oauth2/MSIDBrokerResponse.m
  IdentityCore/src/oauth2/aad_v1/MSIDAADV1BrokerResponse.m
  IdentityCore/src/requests/MSIDTokenResponseHandler.m
  IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.h
  IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOTokenResponseHandler.m
  IdentityCore/src/requests/sdk/MSIDBrokerResponseHandler.h
  IdentityCore/src/requests/sdk/MSIDBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/MSIDTokenRequestProviding.h
  IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h
  IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
  IdentityCore/src/requests/sdk/adal/MSIDLegacyBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/adal/MSIDLegacyTokenRequestProvider.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultTokenRequestProvider.m
  IdentityCore/tests/MSIDDefaultTokenRequestProviderTests.m
  IdentityCore/tests/MSIDLegacyTokenRequestProviderTests.m
  IdentityCore/tests/integration/ios/MSIDBrokerTokenRequestTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m
  IdentityCore/tests/integration/ios/MSIDLegacyBrokerRequestTests.m
  IdentityCore/tests/mocks/MSIDTestTokenRequestProvider.m
Labels: needs-review

#652 Warn on empty issues and PRs
  .github/config.yml
Labels: needs-review

#657 Metadata cache accessor mock changes
  IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.h
  IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.m
Labels: needs-review

#659 Set web config content mode
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
  IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
Labels: msal-1.0.6, needs-review

#660 [ADAL-backport] Set default WKWebView content mode
  .travis.yml
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
  IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
  IdentityCore/tests/util/network/MSIDTestURLSession.h
  IdentityCore/tests/util/network/MSIDTestURLSession.m
  build.py
Labels: ADAL-backport, needs-review

#661 Enable dogfood authenticator support by default
  IdentityCore/src/controllers/ios/MSIDBrokerInteractiveController.m
Labels: needs-review

#658 Allow optional broker key
  IdentityCore/src/broker_operation/request/MSIDBrokerOperationRequest.h
  IdentityCore/src/broker_operation/request/MSIDBrokerOperationRequest.m
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.h
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.m
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.h
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.m
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.h
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
Labels: SSO-extension, needs-review
