Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2019-07, with the labels that each got.

#488 V2 broker logging improvements
  IdentityCore/src/cache/accessor/MSIDAccountCredentialCache.m
  IdentityCore/src/oauth2/token/MSIDBaseToken.m
Labels: broker

#489 Use ASCII for PKCE instead of UTF8 according to spec
  IdentityCore/src/webview/pkce/MSIDPkce.m
Labels: broker

#491 Don't return AT if ID is missing
  IdentityCore/src/requests/MSIDSilentTokenRequest.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultSilentTokenRequest.m
  IdentityCore/tests/integration/ios/MSIDDefaultSilentTokenRequestTests.m
Labels: broker

#503 Removed unused files
  IdentityCore/src/webview/systemWebview/ios/MSIDSFAuthenticationSession.h
  IdentityCore/src/webview/systemWebview/ios/MSIDSFAuthenticationSession.m
Labels: msal_0.3.0

#505 Make instance aware part of the key of account metadata
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.h
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m
  IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadataCacheItem.h
  IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadataCacheItem.m
  IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
  IdentityCore/tests/MSIDAccountMetadataCacheItemTests.m
  IdentityCore/tests/MSIDCacheItemJsonSerializerTests.m
  IdentityCore/tests/integration/ios/MSIDKeychainTokenCacheIntegrationTests.m
Labels: 0.5.0

#511 Pass enrollmentId in ADAL when saving broker response
  IdentityCore/src/cache/MSIDCacheAccessor.h
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
Labels: adal_2.7.13

#508 Pass webview in notifications
  IdentityCore/src/MSIDNotifications.h
  IdentityCore/src/MSIDNotifications.m
  IdentityCore/src/webview/embeddedWebview/MSIDOAuth2EmbeddedWebviewController.m
  IdentityCore/src/webview/systemWebview/ios/MSIDAuthenticationSession.m
  IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m
  IdentityCore/src/webview/systemWebview/ios/MSIDSystemWebviewController.m
Labels: adal_4.0.0

#509 Small fix for id token format inside schema compliance tests
  IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m
Labels: 0.6.0
