Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2019-10, with the labels that each got.

#580 Fixed static analyser warnings
  IdentityCore/src/cache/mac/MSIDMacCredentialStorageItem.m
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
  IdentityCore/src/claims/MSIDIndividualClaimRequestAdditionalInfo.m
  IdentityCore/src/util/NSJSONSerialization+MSIDExtensions.h
  IdentityCore/src/util/NSURL+MSIDAADUtils.h
  IdentityCore/src/validation/MSIDAuthority+Internal.h
  IdentityCore/src/workplacejoin/ios/MSIDWorkPlaceJoinUtil.m
  IdentityCore/src/workplacejoin/mac/MSIDWorkPlaceJoinUtil.m
Labels: MSAL_1.0.1

#581 Expose instance_aware flag in MSAL config
  IdentityCore/src/configuration/webview/MSIDWebviewConfiguration.h
  IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m
  IdentityCore/tests/MSIDAADV1WebviewFactoryTests.m
  IdentityCore/tests/MSIDAADWebviewFactoryTests.m
  IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.h
  IdentityCore/tests/automation/shared/MSIDAutomationTestRequest.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
Labels: MSAL_1.0.1

#578 Remove arm64e from MSAL main target as it is causing build failures in Xcode 11.1
  IdentityCore/xcconfig/identitycore__common__ios.xcconfig
  IdentityCore/xcconfig/identitycore__idlib__ios.xcconfig
Labels: MSAL_1.0.1

#582 Block swipe to dismiss for auth controller
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
  IdentityCore/src/webview/systemWebview/ios/MSIDSafariViewController.m
Labels: MSAL_1.0.1

#583 Support removing RT from other accessors
  IdentityCore/src/cache/MSIDCacheAccessor.h
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.h
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.h
  IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
Labels: adal_2.7.16

#587 Check for main thread in AADWebViewFactory and disable swipe to cancel for ADAL
  IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
Labels: adal_2.7.16

#591 Updated 1.0.15 changelog
  changelog.txt
Labels: adal_2.7.16

#589 Invoke web session on main thread
  IdentityCore/src/webview/MSIDWebviewAuthorization.m
Labels: MSAL_1.0.1

#592 Merge changes from ADAL 2.7.16 into main common core branch
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/cache/accessor/MSIDLegacyTokenCacheAccessor.m
  IdentityCore/src/oauth2/aad_base/MSIDAADWebviewFactory.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/MSIDLegacyAccessorSSOIntegrationTests.m
  build.py
  changelog.txt
Labels: MSAL_1.0.1

#599 Fixed macOS wipe query to use data protection keychain
  IdentityCore/src/cache/MSIDKeychainTokenCache.m
Labels: msal_1.0.2

#601 Release common core 1.3.7 (MSAL 1.0.2 changes)
  IdentityCore/src/cache/MSIDKeychainTokenCache.m
  changelog.txt
Labels: msal_1.0.2

#596 Configuration, Account Identifier, Authority json serialization
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/MSIDJsonSerializableFactory.h
  IdentityCore/src/MSIDJsonSerializableFactory.m
  IdentityCore/src/MSIDJsonSerializableTypes.h
  IdentityCore/src/MSIDJsonSerializableTypes.m
  IdentityCore/src/broker_operation/MSIDBrokerOperationRequestFactory.h
  IdentityCore/src/broker_operation/MSIDBrokerOperationRequestFactory.m
  IdentityCore/src/broker_operation/request/interactive_token_request/MSIDBrokerOperationInteractiveTokenRequest.m
  IdentityCore/src/broker_operation/request/silent_token_request/MSIDBrokerOperationSilentTokenRequest.m
  IdentityCore/src/broker_operation/request/token_request/MSIDBrokerOperationTokenRequest.m
  IdentityCore/src/configuration/MSIDConfiguration+MSIDJsonSerializable.h
  IdentityCore/src/configuration/MSIDConfiguration.h
  IdentityCore/src/configuration/MSIDConfiguration.m
  IdentityCore/src/oauth2/account/MSIDAccountIdentifier+MSIDJsonSerializable.m
  IdentityCore/src/oauth2/account/MSIDAccountIdentifier.h
  IdentityCore/src/oauth2/account/MSIDAccountIdentifier.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSilentTokenRequest.m
  IdentityCore/src/util/NSDictionary+MSIDQueryItems.m
  IdentityCore/src/validation/MSIDAADAuthority.m
  IdentityCore/src/validation/MSIDADFSAuthority.m
  IdentityCore/src/validation/MSIDAadAuthorityResolver.m
  IdentityCore/src/validation/MSIDAuthority.h
  IdentityCore/src/validation/MSIDAuthority.m
  IdentityCore/src/validation/MSIDAuthorityFactory.m
  IdentityCore/src/validation/MSIDB2CAuthority.m
  IdentityCore/tests/MSIDJsonSerializableFactoryTests.m
Labels: SSO-extension
