Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2020-05, with the labels that each got.

#723 Fixed NTLM crash when app has no keywindow
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/MSIDNTLMHandler.m
  IdentityCore/src/webview/embeddedWebview/ui/MSIDNTLMUIPrompt.h
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDNTLMUIPrompt.m
  IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDNTLMUIPrompt.m
  IdentityCore/tests/MSIDLoggerTests.m
Labels: ADAL-backport

#729 Protect legacy macOS cache (#ADO1001313)
  IdentityCore/src/MSIDExternalAADCacheSeeder.m
  IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m
  IdentityCore/tests/integration/MSIDExternalAADCacheSeederIntegrationTests.m
Labels: needs-review

#726 Support clearing SSO extension cookies
  IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationSignoutFromDeviceRequest.h
  IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationSignoutFromDeviceRequest.m
  IdentityCore/src/controllers/broker/MSIDSSOExtensionSignoutController.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.h
  IdentityCore/src/requests/broker/MSIDSSOExtensionSignoutRequest.m
  IdentityCore/tests/MSIDBrokerOperationSignoutFromDeviceRequestTests.m
  IdentityCore/tests/integration/MSIDSSOExtensionSignoutRequestIntegrationTests.m
Labels: needs-review

#743 Add logging for enrollment id mismatch for access tokens
  IdentityCore/src/intune/MSIDIntuneEnrollmentIdsCache.m
  IdentityCore/src/requests/MSIDSilentTokenRequest.m
Labels: 2005-release

#740 Send client side errors to server telemetry
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/network/MSIDHttpRequest.m
  IdentityCore/src/network/request_server_telemetry/MSIDAADTokenRequestServerTelemetry.h
  IdentityCore/src/network/request_server_telemetry/MSIDAADTokenRequestServerTelemetry.m
  IdentityCore/src/network/request_server_telemetry/MSIDHttpRequestServerTelemetryHandling.h
  IdentityCore/src/network/request_server_telemetry/error_provider/MSIDHttpResponseErrorProvider.h
  IdentityCore/src/network/request_server_telemetry/error_provider/MSIDHttpResponseErrorProvider.m
  IdentityCore/src/network/request_server_telemetry/error_provider/MSIDResponseErrorProviding.h
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2Oauth2Factory.m
  IdentityCore/src/util/NSError+MSIDServerTelemetryError.m
Labels: 2005-release

#739 Added common interface for assymetric key generation
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyGenerating.h
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyGeneratorFactory.h
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyGeneratorFactory.m
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.h
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyKeychainGenerator.m
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyLookupAttributes.h
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyLookupAttributes.m
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.h
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyPair.m
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyPairWithCert.h
  IdentityCore/src/cache/crypto/MSIDAssymetricKeyPairWithCert.m
  IdentityCore/src/cache/crypto/mac/MSIDAssymetricKeyLoginKeychainGenerator.h
  IdentityCore/src/cache/crypto/mac/MSIDAssymetricKeyLoginKeychainGenerator.m
  IdentityCore/tests/MSIDAssymetricKeychainGeneratorTests.m
Labels: needs-review

#748 Updated PRT schema to accomodate protocol ver 3
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/MSIDOAuth2Constants.h
  IdentityCore/src/MSIDOAuth2Constants.m
  IdentityCore/src/cache/token/MSIDPRTCacheItem.h
  IdentityCore/src/cache/token/MSIDPRTCacheItem.m
  IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.h
  IdentityCore/src/oauth2/token/MSIDPrimaryRefreshToken.m
  IdentityCore/tests/MSIDPrimaryRefreshTokenTests.m
  IdentityCore/tests/MSIDURLSessionDelegateTests.m
Labels: needs-review
