Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2020-03, with the labels that each got.

#685 Enable openURL in SSO extension
  IdentityCore/src/util/ios/MSIDAppExtensionUtil.h
  IdentityCore/src/util/ios/MSIDAppExtensionUtil.m
Labels: SSO-extension, needs-review

#687 Always pass SDK capabilities for brokered requests
  IdentityCore/src/controllers/MSIDRequestControllerFactory.m
Labels: SSO-extension, needs-review

#688 Create previous MSAL account from identifier if doesn't exist in cache
  IdentityCore/src/MSIDOAuth2Constants.h
  IdentityCore/src/MSIDOAuth2Constants.m
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.h
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m
  IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadataCacheItem.h
  IdentityCore/src/cache/metadata/accountMetadata/MSIDAccountMetadataCacheItem.m
  IdentityCore/tests/MSIDAccountMetadataCacheAccessorTests.m
  IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.h
  IdentityCore/tests/mocks/MSIDAccountMetadataCacheAccessorMock.m
Labels: flw, needs-review

#693 Bypass cache for account metadata in broker
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.h
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m
  IdentityCore/src/cache/metadata/MSIDMetadataCache.h
  IdentityCore/src/cache/metadata/MSIDMetadataCache.m
  IdentityCore/tests/MSIDAccountMetadataCacheAccessorTests.m
  IdentityCore/tests/util/MSIDTestCacheDataSource.m
Labels: SSO-extension, flw, needs-review

#699 Added extra PkeyAuth logging for cert authorities matching
  IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
Labels: needs-review

#698 Fixed too verbose logging for cache item deserialization
  IdentityCore/src/cache/MSIDKeychainTokenCache.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
Labels: flw, needs-review

#701 Fixed CocoaPods script for MSAL 1.1.0 release
  IdentityCore/src/webview/systemWebview/session/MSIDSystemWebViewControllerFactory.m
  IdentityCore/src/webview/systemWebview/session/MSIDSystemWebviewController.m
Labels: needs-review

#695 Remove SHA-1 dependency from production library
  IdentityCore/src/util/NSData+MSIDExtensions.h
  IdentityCore/src/util/NSData+MSIDExtensions.m
  IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
  IdentityCore/tests/automation/ui_tests_lib/MSIDClientCredentialHelper.m
Labels: needs-review

#694 Fixed static analyser warnings
  IdentityCore/src/MSIDClientSDKType.h
  IdentityCore/src/MSIDJsonSerializableFactory.h
  IdentityCore/src/broker_operation/response/MSIDBrokerOperationResponse.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionRequestDelegate+Internal.h
  IdentityCore/src/util/ASAuthorizationSingleSignOnProvider+MSIDExtensions.h
  IdentityCore/src/webview/systemWebview/session/MSIDSystemWebViewControllerFactory.h
Labels: needs-review

#696 [ADAL] Remove SHA-1 dependency
  IdentityCore/src/util/NSData+MSIDExtensions.h
  IdentityCore/src/util/NSData+MSIDExtensions.m
  IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.h
  IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
  IdentityCore/tests/MSIDLoggerTests.m
  IdentityCore/tests/automation/MSIDClientCredentialHelper.m
Labels: ADAL-backport, needs-review

#697 Fixed macOS keychain teamID logic when app is using App Identifier prefix
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
  IdentityCore/src/util/mac/MSIDKeychainUtil+MacInternal.h
  IdentityCore/src/util/mac/MSIDKeychainUtil.m
  IdentityCore/src/util/mac/MSIDLoginKeychainUtil.h
  IdentityCore/src/util/mac/MSIDLoginKeychainUtil.m
  IdentityCore/tests/mac/MSIDKeychainUtilTests.m
Labels: msal-1.1.1, needs-review

#702 Merge MSAL 1.1.0 release branch back into dev
  IdentityCore/src/cache/MSIDKeychainTokenCache.m
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.h
  IdentityCore/src/cache/metadata/MSIDAccountMetadataCacheAccessor.m
  IdentityCore/src/cache/metadata/MSIDMetadataCache.h
  IdentityCore/src/cache/metadata/MSIDMetadataCache.m
  IdentityCore/src/cache/token/MSIDCredentialCacheItem.m
  IdentityCore/src/webview/systemWebview/session/MSIDSystemWebViewControllerFactory.m
  IdentityCore/src/webview/systemWebview/session/MSIDSystemWebviewController.m
  IdentityCore/src/workplacejoin/MSIDPkeyAuthHelper.m
  IdentityCore/tests/MSIDAccountMetadataCacheAccessorTests.m
  IdentityCore/tests/util/MSIDTestCacheDataSource.m
  changelog.txt
Labels: msal-1.1.1, needs-information, needs-review

#703 Fixed SSO extension swipe down cancellation case
  IdentityCore/src/requests/broker/MSIDSSOExtensionRequestDelegate.m
  IdentityCore/tests/integration/MSIDSSOExtensionSignoutRequestIntegrationTests.m
Labels: SSO-extension, msal-1.1.1, needs-review

#704 Fixed SSO extension + MSIT MFA
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
Labels: SSO-extension, msal-1.1.1, needs-review

#705 Added pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: msal-1.1.1, needs-review

#706 Handle http headers in broker response properly
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2BrokerResponse.h
  IdentityCore/src/oauth2/aad_v2/MSIDAADV2BrokerResponse.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m
Labels: msal-1.1.1

#691 Enable E2E tests for iOS SSO extension and FLW
  IdentityCore/tests/automation/shared/MSIDAutomationAccountsResult.h
  IdentityCore/tests/automation/shared/MSIDAutomationAccountsResult.m
  IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDTestAutomationAccountConfigurationRequest.h
  IdentityCore/tests/automation/ui_tests_lib/lab_api/MSIDTestAutomationAccountConfigurationRequest.m
Labels: SSO-extension, flw, needs-review

#711 Merge 1.4.1 release back into dev
  changelog.txt
Labels: needs-review

#707 Clear in-memory storage on mac
  IdentityCore/src/cache/mac/MSIDMacKeychainTokenCache.m
Labels: needs-information
