Repository AzureAD/microsoft-authentication-library-common-for-objc, pull requests merged in 2020-01, with the labels that each got.

#664 [Blocked for release freeze] Release common core 1.3.1 (MSAL 1.0.6 common core)
  IdentityCore/src/controllers/ios/MSIDBrokerInteractiveController.m
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
  IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
  changelog.txt
Labels: release-freeze

#665 [Blocked for release freeze] Merge 1.3.11 release into dev
  IdentityCore/src/controllers/broker/ios/MSIDBrokerInteractiveController.m
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
  IdentityCore/src/webview/embeddedWebview/ui/mac/MSIDWebviewUIController.m
  changelog.txt
Labels: release-freeze

#656 Fix a corner case for signed out account filtering + more UTs
  IdentityCore/IdentityCore.xcodeproj/project.pbxproj
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
Labels: needs-review

#666 Add option to get all accounts including signed out accounts
  IdentityCore/src/MSIDBrokerConstants.h
  IdentityCore/src/MSIDBrokerConstants.m
  IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationGetAccountsRequest.h
  IdentityCore/src/broker_operation/request/account_request/MSIDBrokerOperationGetAccountsRequest.m
  IdentityCore/tests/MSIDBrokerOperationGetAccountsRequestTests.m
Labels: needs-review

#670 Wait for UIScene to become active before calling signout request
  IdentityCore/src/controllers/broker/MSIDSSOExtensionSignoutController.m
Labels: needs-review

#669 [Broker patch] Fixed account lookups and validation with the same email
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.h
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h
  IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultSilentTokenRequest.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
  build.py
Labels: needs-review

#667 Save Account Metadata from Broker Token Response
  IdentityCore/src/requests/broker/MSIDBrokerTokenRequest.m
  IdentityCore/src/requests/sdk/MSIDBrokerResponseHandler.h
  IdentityCore/src/requests/sdk/MSIDBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.h
  IdentityCore/src/requests/sdk/MSIDTokenResponseValidator.m
  IdentityCore/src/requests/sdk/adal/MSIDLegacyBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerResponseHandler.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultBrokerTokenRequest.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerRequestTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultBrokerResponseHandlerTests.m
Labels: needs-review

#671 Propagate return only signed in accounts flag
  IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.h
  IdentityCore/src/requests/broker/MSIDSSOExtensionGetAccountsRequest.m
  IdentityCore/tests/integration/MSIDSSOExtensionGetAccountsRequestIntegrationTests.m
Labels: needs-review

#675 Fixed cache saving for shared devices
  IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
  IdentityCore/src/requests/MSIDSilentTokenRequest.m
  IdentityCore/src/requests/MSIDTokenResponseHandler.h
  IdentityCore/src/requests/MSIDTokenResponseHandler.m
  IdentityCore/src/requests/broker/MSIDSSOTokenResponseHandler.m
Labels: SSO-extension, needs-review

#672 Merge broker hot fix changes into dev branch
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.h
  IdentityCore/src/cache/accessor/MSIDDefaultTokenCacheAccessor.m
  IdentityCore/src/parameters/MSIDInteractiveTokenRequestParameters.h
  IdentityCore/src/requests/MSIDInteractiveTokenRequest.m
  IdentityCore/src/requests/MSIDTokenResponseHandler.m
  IdentityCore/src/requests/broker/MSIDSSOExtensionInteractiveTokenRequest.m
  IdentityCore/src/requests/sdk/msal/MSIDDefaultSilentTokenRequest.m
  IdentityCore/tests/integration/MSIDDefaultAccessorSSOIntegrationTests.m
  IdentityCore/tests/integration/ios/MSIDDefaultInteractiveTokenRequestTests.m
  changelog.txt
Labels: needs-review

#677 Keyed unarchiver hotfix for 11.2.x iOS versions
  IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
  IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m
  changelog.txt
Labels: needs-review

#680 Merge iOS 11.2 hotfix into dev
  IdentityCore/src/cache/token/MSIDLegacyTokenCacheItem.m
  IdentityCore/src/webview/embeddedWebview/ui/ios/MSIDWebviewUIController.m
  IdentityCore/tests/MSIDLegacyTokenCacheItemTests.m
  changelog.txt
Labels: needs-review
